SET DEFINE OFF
SET FEEDBACK OFF
SET SERVEROUTPUT ON

PROMPT Eliminando todos los objetos del esquema PANPUNTOS...

DECLARE
    TYPE t_nombres IS TABLE OF VARCHAR2(128);

    V_TRIGGERS   t_nombres;
    V_VIEWS      t_nombres;
    V_SECUENCIAS t_nombres;
    V_PAQUETES   t_nombres;
    V_CUERPOS    t_nombres;
    V_TABLAS     t_nombres;
    V_INDICES    t_nombres;

    V_TOTAL  NUMBER := 0;
    V_ERRORS NUMBER := 0;

    PROCEDURE ELIMINAR(P_NOMBRES t_nombres, P_OBJETO VARCHAR2, P_EXTRA VARCHAR2) IS
        V_N NUMBER := 0;
    BEGIN
        FOR I IN 1 .. P_NOMBRES.COUNT LOOP
            BEGIN
                EXECUTE IMMEDIATE 'DROP ' || P_OBJETO || ' ' || P_NOMBRES(I) || ' ' || P_EXTRA;
                V_N := V_N + 1;
            EXCEPTION
                WHEN OTHERS THEN
                    V_ERRORS := V_ERRORS + 1;
            END;
        END LOOP;
        V_TOTAL := V_TOTAL + V_N;
    END;
BEGIN
    SELECT OBJECT_NAME BULK COLLECT INTO V_TRIGGERS
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TRIGGER';
    SELECT OBJECT_NAME BULK COLLECT INTO V_VIEWS
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'VIEW';
    SELECT OBJECT_NAME BULK COLLECT INTO V_SECUENCIAS
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'SEQUENCE';
    SELECT OBJECT_NAME BULK COLLECT INTO V_PAQUETES
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE';
    SELECT OBJECT_NAME BULK COLLECT INTO V_CUERPOS
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE BODY';
    SELECT OBJECT_NAME BULK COLLECT INTO V_TABLAS
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME NOT LIKE 'BIN$%';
    SELECT OBJECT_NAME BULK COLLECT INTO V_INDICES
      FROM USER_OBJECTS WHERE OBJECT_TYPE = 'INDEX';

    ELIMINAR(V_TRIGGERS,   'TRIGGER',      '');
    ELIMINAR(V_VIEWS,      'VIEW',         '');
    ELIMINAR(V_CUERPOS,    'PACKAGE BODY', '');
    ELIMINAR(V_PAQUETES,   'PACKAGE',      '');
    ELIMINAR(V_SECUENCIAS, 'SEQUENCE',     '');
    ELIMINAR(V_TABLAS,     'TABLE',        'CASCADE CONSTRAINTS');
    ELIMINAR(V_INDICES,    'INDEX',        '');

    DBMS_OUTPUT.PUT_LINE('Objetos eliminados: ' || V_TOTAL);
    IF V_ERRORS > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Objetos omitidos: ' || V_ERRORS);
    END IF;
END;
/

PURGE RECYCLEBIN;

DECLARE
    V_RESTANTES NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_RESTANTES FROM USER_OBJECTS;
    IF V_RESTANTES = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Esquema vacio, listo para reinstalar');
    ELSE
        DBMS_OUTPUT.PUT_LINE('AVISO: quedan ' || V_RESTANTES || ' objeto(s) sin eliminar');
    END IF;
END;
/
