CREATE TABLE CLIENTE (
    ID_CLIENTE      NUMBER(10)     NOT NULL,
    DPI             VARCHAR2(20)   NOT NULL,
    NOMBRE          VARCHAR2(120)  NOT NULL,
    TELEFONO        VARCHAR2(30),
    EMAIL           VARCHAR2(120),
    SALDO_PUNTOS    NUMBER(10)     DEFAULT 0 NOT NULL,
    ESTADO          VARCHAR2(10)   DEFAULT 'ACTIVO' NOT NULL,
    FECHA_REGISTRO  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_CLIENTE_DPI UNIQUE (DPI)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO       NUMBER(10)    NOT NULL,
    CODIGO            VARCHAR2(20)  NOT NULL,
    NOMBRE            VARCHAR2(120) NOT NULL,
    CATEGORIA         VARCHAR2(20)  NOT NULL,
    PRECIO_UNITARIO   NUMBER(10,2)  DEFAULT 0 NOT NULL,
    EXISTENCIA        NUMBER(10)    DEFAULT 0 NOT NULL,
    ESTADO            VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT UQ_PRODUCTO_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE MENU (
    ID_MENU        NUMBER(10)    NOT NULL,
    CODIGO         VARCHAR2(20)  NOT NULL,
    NOMBRE         VARCHAR2(120) NOT NULL,
    PRECIO_MENU    NUMBER(10,2)  DEFAULT 0 NOT NULL,
    ESTADO         VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_MENU PRIMARY KEY (ID_MENU),
    CONSTRAINT UQ_MENU_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE DETALLE_MENU (
    ID_MENU      NUMBER(10) NOT NULL,
    ID_PRODUCTO  NUMBER(10) NOT NULL,
    CANTIDAD     NUMBER(10) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DETALLE_MENU PRIMARY KEY (ID_MENU, ID_PRODUCTO)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO          NUMBER(10)   NOT NULL,
    ID_CLIENTE         NUMBER(10)   NOT NULL,
    FECHA_PEDIDO       DATE         DEFAULT SYSDATE NOT NULL,
    SUBTOTAL           NUMBER(10,2) DEFAULT 0 NOT NULL,
    TOTAL              NUMBER(10,2) DEFAULT 0 NOT NULL,
    PUNTOS_GENERADOS   NUMBER(10)   DEFAULT 0 NOT NULL,
    ESTADO             VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE       NUMBER(10)   NOT NULL,
    ID_PEDIDO        NUMBER(10)   NOT NULL,
    TIPO_ITEM        VARCHAR2(20) NOT NULL,
    ID_PRODUCTO      NUMBER(10),
    ID_MENU          NUMBER(10),
    CANTIDAD         NUMBER(10)   NOT NULL,
    PRECIO_UNITARIO  NUMBER(10,2) NOT NULL,
    SUBTOTAL         NUMBER(10,2) NOT NULL,
    PUNTOS           NUMBER(10)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETALLE)
);

CREATE TABLE PAGO (
    ID_PAGO             NUMBER(10)   NOT NULL,
    ID_PEDIDO           NUMBER(10)   NOT NULL,
    TIPO_PAGO           VARCHAR2(10) NOT NULL,
    MONTO               NUMBER(10,2) NOT NULL,
    EFECTIVO_RECIBIDO   NUMBER(10,2),
    CAMBIO              NUMBER(10,2) DEFAULT 0 NOT NULL,
    REFERENCIA          VARCHAR2(40),
    ESTADO              VARCHAR2(10) NOT NULL,
    FECHA_PAGO          DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO)
);

CREATE TABLE MOVIMIENTO_PUNTOS (
    ID_MOVIMIENTO      NUMBER(10)  NOT NULL,
    ID_CLIENTE         NUMBER(10)  NOT NULL,
    TIPO_MOVIMIENTO    VARCHAR2(20) NOT NULL,
    PUNTOS             NUMBER(10)  NOT NULL,
    SALDO_RESULTANTE   NUMBER(10)  NOT NULL,
    REFERENCIA         VARCHAR2(60),
    FECHA_MOVIMIENTO   DATE        DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MOVIMIENTO_PUNTOS PRIMARY KEY (ID_MOVIMIENTO)
);

CREATE TABLE RECOMPENSA (
    ID_RECOMPENSA      NUMBER(10)   NOT NULL,
    CODIGO             VARCHAR2(20) NOT NULL,
    NOMBRE             VARCHAR2(120) NOT NULL,
    TIPO_ITEM          VARCHAR2(20) NOT NULL,
    ID_PRODUCTO        NUMBER(10),
    ID_MENU            NUMBER(10),
    PUNTOS_NECESARIOS  NUMBER(10)   NOT NULL,
    ESTADO             VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_RECOMPENSA PRIMARY KEY (ID_RECOMPENSA),
    CONSTRAINT UQ_RECOMPENSA_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE CANJE (
    ID_CANJE         NUMBER(10) NOT NULL,
    ID_CLIENTE       NUMBER(10) NOT NULL,
    ID_RECOMPENSA    NUMBER(10) NOT NULL,
    PUNTOS_USADOS    NUMBER(10) NOT NULL,
    FECHA_CANJE      DATE       DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CANJE PRIMARY KEY (ID_CANJE)
);

CREATE TABLE MOVIMIENTO_INVENTARIO (
    ID_MOVIMIENTO        NUMBER(10)   NOT NULL,
    ID_PRODUCTO          NUMBER(10)   NOT NULL,
    TIPO_MOVIMIENTO      VARCHAR2(20) NOT NULL,
    CANTIDAD             NUMBER(10)   NOT NULL,
    EXISTENCIA_ANTERIOR  NUMBER(10)   NOT NULL,
    EXISTENCIA_NUEVA     NUMBER(10)   NOT NULL,
    REFERENCIA           VARCHAR2(60),
    FECHA_MOVIMIENTO     DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MOVIMIENTO_INVENTARIO PRIMARY KEY (ID_MOVIMIENTO)
);
