ALTER TABLE DETALLE_MENU
    ADD CONSTRAINT FK_DETALLE_MENU_MENU FOREIGN KEY (ID_MENU)
    REFERENCES MENU (ID_MENU) ON DELETE CASCADE;

ALTER TABLE DETALLE_MENU
    ADD CONSTRAINT FK_DETALLE_MENU_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE PEDIDO
    ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO)
    REFERENCES PEDIDO (ID_PEDIDO) ON DELETE CASCADE;

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT FK_DETALLE_PEDIDO_MENU FOREIGN KEY (ID_MENU)
    REFERENCES MENU (ID_MENU);

ALTER TABLE PAGO
    ADD CONSTRAINT FK_PAGO_PEDIDO FOREIGN KEY (ID_PEDIDO)
    REFERENCES PEDIDO (ID_PEDIDO);

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT FK_MOV_PUNTOS_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE RECOMPENSA
    ADD CONSTRAINT FK_RECOMPENSA_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE RECOMPENSA
    ADD CONSTRAINT FK_RECOMPENSA_MENU FOREIGN KEY (ID_MENU)
    REFERENCES MENU (ID_MENU);

ALTER TABLE CANJE
    ADD CONSTRAINT FK_CANJE_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE CANJE
    ADD CONSTRAINT FK_CANJE_RECOMPENSA FOREIGN KEY (ID_RECOMPENSA)
    REFERENCES RECOMPENSA (ID_RECOMPENSA);

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT FK_MOV_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);
