ALTER TABLE PRODUCTO
    ADD CONSTRAINT CK_PRODUCTO_CATEGORIA
    CHECK (CATEGORIA IN ('SANDWICH', 'BEBIDA', 'ACOMPANAMIENTO'));

ALTER TABLE PRODUCTO
    ADD CONSTRAINT CK_PRODUCTO_PRECIO
    CHECK (PRECIO_UNITARIO >= 0);

ALTER TABLE PRODUCTO
    ADD CONSTRAINT CK_PRODUCTO_EXISTENCIA
    CHECK (EXISTENCIA >= 0);

ALTER TABLE PRODUCTO
    ADD CONSTRAINT CK_PRODUCTO_ESTADO
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE MENU
    ADD CONSTRAINT CK_MENU_PRECIO
    CHECK (PRECIO_MENU >= 0);

ALTER TABLE MENU
    ADD CONSTRAINT CK_MENU_ESTADO
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE DETALLE_MENU
    ADD CONSTRAINT CK_DETALLE_MENU_CANTIDAD
    CHECK (CANTIDAD > 0);

ALTER TABLE CLIENTE
    ADD CONSTRAINT CK_CLIENTE_SALDO
    CHECK (SALDO_PUNTOS >= 0);

ALTER TABLE CLIENTE
    ADD CONSTRAINT CK_CLIENTE_ESTADO
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO'));

ALTER TABLE PEDIDO
    ADD CONSTRAINT CK_PEDIDO_ESTADO
    CHECK (ESTADO IN ('PENDIENTE', 'PAGADO', 'ENTREGADO', 'ANULADO'));

ALTER TABLE PEDIDO
    ADD CONSTRAINT CK_PEDIDO_TOTAL
    CHECK (SUBTOTAL >= 0 AND TOTAL >= 0);

ALTER TABLE PEDIDO
    ADD CONSTRAINT CK_PEDIDO_PUNTOS
    CHECK (PUNTOS_GENERADOS >= 0);

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT CK_DETALLE_TIPO_ITEM
    CHECK (
        (TIPO_ITEM = 'PRODUCTO' AND ID_PRODUCTO IS NOT NULL AND ID_MENU IS NULL)
        OR
        (TIPO_ITEM = 'MENU' AND ID_MENU IS NOT NULL AND ID_PRODUCTO IS NULL)
    );

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT CK_DETALLE_CANTIDAD
    CHECK (CANTIDAD > 0);

ALTER TABLE DETALLE_PEDIDO
    ADD CONSTRAINT CK_DETALLE_SUBTOTAL
    CHECK (PRECIO_UNITARIO >= 0 AND SUBTOTAL >= 0);

ALTER TABLE PAGO
    ADD CONSTRAINT CK_PAGO_TIPO
    CHECK (TIPO_PAGO IN ('EFECTIVO', 'TARJETA'));

ALTER TABLE PAGO
    ADD CONSTRAINT CK_PAGO_ESTADO
    CHECK (ESTADO IN ('APROBADO', 'RECHAZADO'));

ALTER TABLE PAGO
    ADD CONSTRAINT CK_PAGO_MONTO
    CHECK (MONTO > 0);

ALTER TABLE PAGO
    ADD CONSTRAINT CK_PAGO_TARJETA_REF
    CHECK (TIPO_PAGO <> 'TARJETA' OR REFERENCIA IS NOT NULL);

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT CK_MOV_PUNTOS_TIPO
    CHECK (TIPO_MOVIMIENTO IN ('ACUMULACION', 'CANJE', 'AJUSTE'));

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT CK_MOV_PUNTOS_CANTIDAD
    CHECK (PUNTOS <> 0);

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT CK_MOV_PUNTOS_ACUMULACION
    CHECK (TIPO_MOVIMIENTO <> 'ACUMULACION' OR PUNTOS > 0);

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT CK_MOV_PUNTOS_CANJE
    CHECK (TIPO_MOVIMIENTO <> 'CANJE' OR PUNTOS < 0);

ALTER TABLE MOVIMIENTO_PUNTOS
    ADD CONSTRAINT CK_MOV_PUNTOS_SALDO_RESULTANTE
    CHECK (SALDO_RESULTANTE >= 0);

ALTER TABLE RECOMPENSA
    ADD CONSTRAINT CK_RECOMPENSA_TIPO
    CHECK (
        (TIPO_ITEM = 'PRODUCTO' AND ID_PRODUCTO IS NOT NULL AND ID_MENU IS NULL)
        OR
        (TIPO_ITEM = 'MENU' AND ID_MENU IS NOT NULL AND ID_PRODUCTO IS NULL)
    );

ALTER TABLE RECOMPENSA
    ADD CONSTRAINT CK_RECOMPENSA_PUNTOS
    CHECK (PUNTOS_NECESARIOS > 0);

ALTER TABLE RECOMPENSA
    ADD CONSTRAINT CK_RECOMPENSA_ESTADO
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'));

ALTER TABLE CANJE
    ADD CONSTRAINT CK_CANJE_PUNTOS
    CHECK (PUNTOS_USADOS > 0);

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT CK_MOV_INV_TIPO
    CHECK (TIPO_MOVIMIENTO IN ('ABASTECIMIENTO', 'VENTA', 'CANJE', 'AJUSTE'));

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT CK_MOV_INV_CANTIDAD
    CHECK (CANTIDAD <> 0);

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT CK_MOV_INV_ENTRADA
    CHECK (TIPO_MOVIMIENTO <> 'ABASTECIMIENTO' OR CANTIDAD > 0);

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT CK_MOV_INV_SALIDA
    CHECK (TIPO_MOVIMIENTO = 'ABASTECIMIENTO' OR CANTIDAD < 0);

ALTER TABLE MOVIMIENTO_INVENTARIO
    ADD CONSTRAINT CK_MOV_INV_EXISTENCIAS
    CHECK (EXISTENCIA_ANTERIOR >= 0 AND EXISTENCIA_NUEVA >= 0);
