CREATE INDEX IX_PEDIDO_CLIENTE      ON PEDIDO (ID_CLIENTE);
CREATE INDEX IX_PEDIDO_FECHA        ON PEDIDO (FECHA_PEDIDO);
CREATE INDEX IX_PEDIDO_ESTADO       ON PEDIDO (ESTADO);
CREATE INDEX IX_DETALLE_PEDIDO_ITEM ON DETALLE_PEDIDO (ID_PEDIDO);
CREATE INDEX IX_PAGO_PEDIDO         ON PAGO (ID_PEDIDO);
CREATE INDEX IX_MOV_PUNTOS_CLIENTE  ON MOVIMIENTO_PUNTOS (ID_CLIENTE, FECHA_MOVIMIENTO);
CREATE INDEX IX_MOV_INV_PRODUCTO    ON MOVIMIENTO_INVENTARIO (ID_PRODUCTO, FECHA_MOVIMIENTO);
CREATE INDEX IX_CANJE_CLIENTE       ON CANJE (ID_CLIENTE, FECHA_CANJE);
CREATE INDEX IX_PRODUCTO_CATEGORIA  ON PRODUCTO (CATEGORIA, ESTADO);
