CREATE OR REPLACE PACKAGE PK_INVENTARIO AS
    PROCEDURE ABASTECER(
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_CANTIDAD    IN NUMBER,
        P_REFERENCIA  IN VARCHAR2
    );
    PROCEDURE DESCONTAR(
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_CANTIDAD    IN NUMBER,
        P_TIPO_MOV    IN VARCHAR2,
        P_REFERENCIA  IN VARCHAR2
    );
    PROCEDURE DESCONTAR_MENU(
        P_ID_MENU    IN MENU.ID_MENU%TYPE,
        P_CANTIDAD   IN NUMBER,
        P_TIPO_MOV   IN VARCHAR2,
        P_REFERENCIA IN VARCHAR2
    );
    PROCEDURE VALIDAR_ITEM(
        P_TIPO_ITEM   IN VARCHAR2,
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_ID_MENU     IN MENU.ID_MENU%TYPE
    );
END PK_INVENTARIO;
/
CREATE OR REPLACE PACKAGE BODY PK_INVENTARIO AS

    PROCEDURE DESCONTAR(
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_CANTIDAD    IN NUMBER,
        P_TIPO_MOV    IN VARCHAR2,
        P_REFERENCIA  IN VARCHAR2
    ) IS
        V_NOMBRE      VARCHAR2(120);
        V_ESTADO      VARCHAR2(10);
        V_EXISTENCIA  NUMBER(10);
    BEGIN
        SELECT NOMBRE, ESTADO, EXISTENCIA
          INTO V_NOMBRE, V_ESTADO, V_EXISTENCIA
          FROM PRODUCTO
         WHERE ID_PRODUCTO = P_ID_PRODUCTO
           FOR UPDATE;

        IF V_NOMBRE IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'El producto indicado no existe.');
        END IF;

        IF V_ESTADO <> 'ACTIVO' THEN
            RAISE_APPLICATION_ERROR(-20002, 'El producto "' || V_NOMBRE || '" esta desactivado.');
        END IF;

        IF V_EXISTENCIA < P_CANTIDAD THEN
            RAISE_APPLICATION_ERROR(-20003,
                'Existencias insuficientes de "' || V_NOMBRE || '". Disponible: ' || V_EXISTENCIA || '.');
        END IF;

        UPDATE PRODUCTO
           SET EXISTENCIA = EXISTENCIA - P_CANTIDAD
         WHERE ID_PRODUCTO = P_ID_PRODUCTO;

        INSERT INTO MOVIMIENTO_INVENTARIO (
            ID_MOVIMIENTO, ID_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD,
            EXISTENCIA_ANTERIOR, EXISTENCIA_NUEVA, REFERENCIA, FECHA_MOVIMIENTO
        ) VALUES (
            SEQ_MOV_INVENTARIO.NEXTVAL, P_ID_PRODUCTO, P_TIPO_MOV, -P_CANTIDAD,
            V_EXISTENCIA, V_EXISTENCIA - P_CANTIDAD, P_REFERENCIA, SYSDATE
        );
    END DESCONTAR;

    PROCEDURE ABASTECER(
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_CANTIDAD    IN NUMBER,
        P_REFERENCIA  IN VARCHAR2
    ) IS
        V_NOMBRE      VARCHAR2(120);
        V_ESTADO      VARCHAR2(10);
        V_EXISTENCIA  NUMBER(10);
    BEGIN
        IF P_CANTIDAD IS NULL OR P_CANTIDAD <= 0 THEN
            RAISE_APPLICATION_ERROR(-20004, 'La cantidad de abastecimiento debe ser mayor que cero.');
        END IF;

        SELECT NOMBRE, ESTADO, EXISTENCIA
          INTO V_NOMBRE, V_ESTADO, V_EXISTENCIA
          FROM PRODUCTO
         WHERE ID_PRODUCTO = P_ID_PRODUCTO
         FOR UPDATE;

        IF V_NOMBRE IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'El producto indicado no existe.');
        END IF;

        IF V_ESTADO <> 'ACTIVO' THEN
            RAISE_APPLICATION_ERROR(-20002, 'El producto "' || V_NOMBRE || '" esta desactivado.');
        END IF;

        UPDATE PRODUCTO
           SET EXISTENCIA = EXISTENCIA + P_CANTIDAD
         WHERE ID_PRODUCTO = P_ID_PRODUCTO;

        INSERT INTO MOVIMIENTO_INVENTARIO (
            ID_MOVIMIENTO, ID_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD,
            EXISTENCIA_ANTERIOR, EXISTENCIA_NUEVA, REFERENCIA, FECHA_MOVIMIENTO
        ) VALUES (
            SEQ_MOV_INVENTARIO.NEXTVAL, P_ID_PRODUCTO, 'ABASTECIMIENTO', P_CANTIDAD,
            V_EXISTENCIA, V_EXISTENCIA + P_CANTIDAD, P_REFERENCIA, SYSDATE
        );
    END ABASTECER;

    PROCEDURE DESCONTAR_MENU(
        P_ID_MENU    IN MENU.ID_MENU%TYPE,
        P_CANTIDAD   IN NUMBER,
        P_TIPO_MOV   IN VARCHAR2,
        P_REFERENCIA IN VARCHAR2
    ) IS
        V_NOMBRE   VARCHAR2(120);
        V_ESTADO   VARCHAR2(10);
        V_TOTAL    NUMBER(10);
    BEGIN
        SELECT NOMBRE, ESTADO INTO V_NOMBRE, V_ESTADO
          FROM MENU WHERE ID_MENU = P_ID_MENU;

        IF V_NOMBRE IS NULL THEN
            RAISE_APPLICATION_ERROR(-20005, 'El menu indicado no existe.');
        END IF;

        IF V_ESTADO <> 'ACTIVO' THEN
            RAISE_APPLICATION_ERROR(-20006, 'El menu "' || V_NOMBRE || '" esta desactivado.');
        END IF;

        SELECT NVL(SUM(CANTIDAD), 0) INTO V_TOTAL FROM DETALLE_MENU WHERE ID_MENU = P_ID_MENU;

        IF V_TOTAL = 0 THEN
            RAISE_APPLICATION_ERROR(-20007, 'El menu "' || V_NOMBRE || '" no tiene componentes configurados.');
        END IF;

        FOR R IN (SELECT ID_PRODUCTO, CANTIDAD FROM DETALLE_MENU WHERE ID_MENU = P_ID_MENU) LOOP
            DESCONTAR(R.ID_PRODUCTO, R.CANTIDAD * P_CANTIDAD, P_TIPO_MOV, P_REFERENCIA);
        END LOOP;
    END DESCONTAR_MENU;

    PROCEDURE VALIDAR_ITEM(
        P_TIPO_ITEM   IN VARCHAR2,
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_ID_MENU     IN MENU.ID_MENU%TYPE
    ) IS
        V_ESTADO VARCHAR2(10);
    BEGIN
        IF P_TIPO_ITEM = 'PRODUCTO' THEN
            SELECT ESTADO INTO V_ESTADO FROM PRODUCTO WHERE ID_PRODUCTO = P_ID_PRODUCTO;
            IF V_ESTADO IS NULL THEN
                RAISE_APPLICATION_ERROR(-20001, 'El producto indicado no existe.');
            END IF;
            IF V_ESTADO <> 'ACTIVO' THEN
                RAISE_APPLICATION_ERROR(-20002, 'El producto esta desactivado.');
            END IF;
        ELSE
            SELECT ESTADO INTO V_ESTADO FROM MENU WHERE ID_MENU = P_ID_MENU;
            IF V_ESTADO IS NULL THEN
                RAISE_APPLICATION_ERROR(-20005, 'El menu indicado no existe.');
            END IF;
            IF V_ESTADO <> 'ACTIVO' THEN
                RAISE_APPLICATION_ERROR(-20006, 'El menu esta desactivado.');
            END IF;
        END IF;
    END VALIDAR_ITEM;

END PK_INVENTARIO;
/
