CREATE OR REPLACE PACKAGE PK_PUNTOS AS
    PROCEDURE ACREDITAR(
        P_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
        P_PUNTOS    IN NUMBER,
        P_REFERENCIA IN VARCHAR2
    );
    PROCEDURE DESCONTAR(
        P_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
        P_PUNTOS    IN NUMBER,
        P_REFERENCIA IN VARCHAR2
    );
END PK_PUNTOS;
/
CREATE OR REPLACE PACKAGE BODY PK_PUNTOS AS

    PROCEDURE ACREDITAR(
        P_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
        P_PUNTOS    IN NUMBER,
        P_REFERENCIA IN VARCHAR2
    ) IS
        V_SALDO NUMBER(10);
    BEGIN
        IF P_PUNTOS IS NULL OR P_PUNTOS <= 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'La cantidad de puntos a acreditar debe ser mayor que cero.');
        END IF;

        SELECT SALDO_PUNTOS INTO V_SALDO
          FROM CLIENTE WHERE ID_CLIENTE = P_ID_CLIENTE FOR UPDATE;

        IF V_SALDO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20011, 'El cliente indicado no existe.');
        END IF;

        INSERT INTO MOVIMIENTO_PUNTOS (
            ID_MOVIMIENTO, ID_CLIENTE, TIPO_MOVIMIENTO, PUNTOS,
            SALDO_RESULTANTE, REFERENCIA, FECHA_MOVIMIENTO
        ) VALUES (
            SEQ_MOV_PUNTOS.NEXTVAL, P_ID_CLIENTE, 'ACUMULACION', P_PUNTOS,
            V_SALDO + P_PUNTOS, P_REFERENCIA, SYSDATE
        );
    END ACREDITAR;

    PROCEDURE DESCONTAR(
        P_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
        P_PUNTOS    IN NUMBER,
        P_REFERENCIA IN VARCHAR2
    ) IS
        V_SALDO NUMBER(10);
    BEGIN
        IF P_PUNTOS IS NULL OR P_PUNTOS <= 0 THEN
            RAISE_APPLICATION_ERROR(-20012, 'La cantidad de puntos a descontar debe ser mayor que cero.');
        END IF;

        SELECT SALDO_PUNTOS INTO V_SALDO
          FROM CLIENTE WHERE ID_CLIENTE = P_ID_CLIENTE FOR UPDATE;

        IF V_SALDO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20011, 'El cliente indicado no existe.');
        END IF;

        IF V_SALDO < P_PUNTOS THEN
            RAISE_APPLICATION_ERROR(-20013,
                'Puntos insuficientes. Disponibles: ' || V_SALDO || '. Requeridos: ' || P_PUNTOS || '.');
        END IF;

        INSERT INTO MOVIMIENTO_PUNTOS (
            ID_MOVIMIENTO, ID_CLIENTE, TIPO_MOVIMIENTO, PUNTOS,
            SALDO_RESULTANTE, REFERENCIA, FECHA_MOVIMIENTO
        ) VALUES (
            SEQ_MOV_PUNTOS.NEXTVAL, P_ID_CLIENTE, 'CANJE', -P_PUNTOS,
            V_SALDO - P_PUNTOS, P_REFERENCIA, SYSDATE
        );
    END DESCONTAR;

END PK_PUNTOS;
/
