CREATE OR REPLACE TRIGGER TRG_MOV_PUNTOS_SALDO
AFTER INSERT ON MOVIMIENTO_PUNTOS
FOR EACH ROW
BEGIN
    UPDATE CLIENTE
       SET SALDO_PUNTOS = SALDO_PUNTOS + :NEW.PUNTOS
     WHERE ID_CLIENTE = :NEW.ID_CLIENTE;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'El cliente indicado no existe.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_PEDIDO_PAGO
AFTER UPDATE OF ESTADO ON PEDIDO
FOR EACH ROW
WHEN (NEW.ESTADO = 'PAGADO' AND OLD.ESTADO <> 'PAGADO')
DECLARE
    V_REFERENCIA VARCHAR2(60);
BEGIN
    V_REFERENCIA := 'PED-' || TO_CHAR(:NEW.ID_PEDIDO);

    FOR R IN (SELECT TIPO_ITEM, ID_PRODUCTO, ID_MENU, CANTIDAD
                FROM DETALLE_PEDIDO
               WHERE ID_PEDIDO = :NEW.ID_PEDIDO) LOOP
        IF R.TIPO_ITEM = 'PRODUCTO' THEN
            PK_INVENTARIO.DESCONTAR(R.ID_PRODUCTO, R.CANTIDAD, 'VENTA', V_REFERENCIA);
        ELSE
            PK_INVENTARIO.DESCONTAR_MENU(R.ID_MENU, R.CANTIDAD, 'VENTA', V_REFERENCIA);
        END IF;
    END LOOP;

    IF :NEW.PUNTOS_GENERADOS > 0 THEN
        PK_PUNTOS.ACREDITAR(:NEW.ID_CLIENTE, :NEW.PUNTOS_GENERADOS, V_REFERENCIA);
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_CLIENTE_PROTEGIDO
BEFORE DELETE ON CLIENTE
FOR EACH ROW
DECLARE
    V_PEDIDOS  NUMBER(10);
    V_MOVIMIENTOS NUMBER(10);
BEGIN
    SELECT COUNT(*) INTO V_PEDIDOS FROM PEDIDO WHERE ID_CLIENTE = :OLD.ID_CLIENTE;
    SELECT COUNT(*) INTO V_MOVIMIENTOS FROM MOVIMIENTO_PUNTOS WHERE ID_CLIENTE = :OLD.ID_CLIENTE;

    IF V_PEDIDOS > 0 OR V_MOVIMIENTOS > 0 THEN
        RAISE_APPLICATION_ERROR(-20020,
            'No se puede eliminar el cliente: posee ' || V_PEDIDOS || ' pedido(s) y ' ||
            V_MOVIMIENTOS || ' movimiento(s) de puntos. Utilice la desactivacion.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_PEDIDO_ESTADO
BEFORE UPDATE OF ESTADO ON PEDIDO
FOR EACH ROW
DECLARE
    V_PERMITIDA BOOLEAN;
BEGIN
    IF :NEW.ESTADO = :OLD.ESTADO THEN
        RETURN;
    END IF;

    V_PERMITIDA :=
        (:OLD.ESTADO = 'PENDIENTE' AND :NEW.ESTADO IN ('PAGADO', 'ANULADO'))
        OR
        (:OLD.ESTADO = 'PAGADO' AND :NEW.ESTADO = 'ENTREGADO');

    IF NOT V_PERMITIDA THEN
        RAISE_APPLICATION_ERROR(-20021,
            'Transicion de estado no permitida: ' || :OLD.ESTADO || ' -> ' || :NEW.ESTADO || '.');
    END IF;
END;
/
