INSERT INTO CLIENTE (ID_CLIENTE, DPI, NOMBRE, TELEFONO, EMAIL, ESTADO) VALUES (SEQ_CLIENTE.NEXTVAL, '12345678-1', 'Juan Perez Lopez',        '5555-1001', 'juanperez@correo.com',      'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, DPI, NOMBRE, TELEFONO, EMAIL, ESTADO) VALUES (SEQ_CLIENTE.NEXTVAL, '12345678-2', 'Maria Garcia Sanchez',     '5555-1002', 'mariagarcia@correo.com',   'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, DPI, NOMBRE, TELEFONO, EMAIL, ESTADO) VALUES (SEQ_CLIENTE.NEXTVAL, '12345678-3', 'Carlos Ramirez Flores',    '5555-1003', 'carlosramirez@correo.com',  'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, DPI, NOMBRE, TELEFONO, EMAIL, ESTADO) VALUES (SEQ_CLIENTE.NEXTVAL, '12345678-4', 'Ana Lucia Martinez',       '5555-1004', 'analucia@correo.com',       'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, DPI, NOMBRE, TELEFONO, EMAIL, ESTADO) VALUES (SEQ_CLIENTE.NEXTVAL, '12345678-5', 'Luis Gomez Estrada',        '5555-1005', 'luisgomez@correo.com',      'INACTIVO');

INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'SAND-001', 'Sandwich de pollo',   'SANDWICH',      25.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'SAND-002', 'Sandwich de jamon',   'SANDWICH',      22.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'SAND-003', 'Sandwich de pavo',    'SANDWICH',      28.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'BEB-001',  'Gaseosa individual',  'BEBIDA',         8.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'BEB-002',  'Jugo de naranja',     'BEBIDA',        10.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'ACO-001',  'Papas fritas',        'ACOMPANAMIENTO', 12.00, 0, 'ACTIVO');
INSERT INTO PRODUCTO (ID_PRODUCTO, CODIGO, NOMBRE, CATEGORIA, PRECIO_UNITARIO, EXISTENCIA, ESTADO) VALUES (SEQ_PRODUCTO.NEXTVAL, 'ACO-002',  'Ensalada de tuna',    'ACOMPANAMIENTO', 14.00, 0, 'ACTIVO');

INSERT INTO MENU (ID_MENU, CODIGO, NOMBRE, PRECIO_MENU, ESTADO) VALUES (SEQ_MENU.NEXTVAL, 'MEN-001', 'Menu completo de pollo', 37.00, 'ACTIVO');
INSERT INTO MENU (ID_MENU, CODIGO, NOMBRE, PRECIO_MENU, ESTADO) VALUES (SEQ_MENU.NEXTVAL, 'MEN-002', 'Menu completo de jamon', 34.00, 'ACTIVO');
INSERT INTO MENU (ID_MENU, CODIGO, NOMBRE, PRECIO_MENU, ESTADO) VALUES (SEQ_MENU.NEXTVAL, 'MEN-003', 'Menu completo mixto',    39.00, 'ACTIVO');

INSERT INTO DETALLE_MENU (ID_MENU, ID_PRODUCTO, CANTIDAD)
SELECT M.ID_MENU, P.ID_PRODUCTO, 1
  FROM MENU M, PRODUCTO P
 WHERE (M.CODIGO = 'MEN-001' AND P.CODIGO = 'SAND-001')
    OR (M.CODIGO = 'MEN-001' AND P.CODIGO = 'BEB-001')
    OR (M.CODIGO = 'MEN-001' AND P.CODIGO = 'ACO-001')
    OR (M.CODIGO = 'MEN-002' AND P.CODIGO = 'SAND-002')
    OR (M.CODIGO = 'MEN-002' AND P.CODIGO = 'BEB-001')
    OR (M.CODIGO = 'MEN-002' AND P.CODIGO = 'ACO-001')
    OR (M.CODIGO = 'MEN-003' AND P.CODIGO = 'SAND-003')
    OR (M.CODIGO = 'MEN-003' AND P.CODIGO = 'BEB-002')
    OR (M.CODIGO = 'MEN-003' AND P.CODIGO = 'ACO-002');

INSERT INTO RECOMPENSA (ID_RECOMPENSA, CODIGO, NOMBRE, TIPO_ITEM, ID_PRODUCTO, ID_MENU, PUNTOS_NECESARIOS) VALUES (SEQ_RECOMPENSA.NEXTVAL, 'REC-001', 'Bebida gratuita',             'PRODUCTO', (SELECT ID_PRODUCTO FROM PRODUCTO WHERE CODIGO = 'BEB-001'),  NULL, 10);
INSERT INTO RECOMPENSA (ID_RECOMPENSA, CODIGO, NOMBRE, TIPO_ITEM, ID_PRODUCTO, ID_MENU, PUNTOS_NECESARIOS) VALUES (SEQ_RECOMPENSA.NEXTVAL, 'REC-002', 'Acompanamiento gratuito',     'PRODUCTO', (SELECT ID_PRODUCTO FROM PRODUCTO WHERE CODIGO = 'ACO-001'),  NULL, 15);
INSERT INTO RECOMPENSA (ID_RECOMPENSA, CODIGO, NOMBRE, TIPO_ITEM, ID_PRODUCTO, ID_MENU, PUNTOS_NECESARIOS) VALUES (SEQ_RECOMPENSA.NEXTVAL, 'REC-003', 'Sandwich individual gratuito','PRODUCTO',(SELECT ID_PRODUCTO FROM PRODUCTO WHERE CODIGO = 'SAND-001'), NULL, 30);
INSERT INTO RECOMPENSA (ID_RECOMPENSA, CODIGO, NOMBRE, TIPO_ITEM, ID_PRODUCTO, ID_MENU, PUNTOS_NECESARIOS) VALUES (SEQ_RECOMPENSA.NEXTVAL, 'REC-004', 'Menu completo gratuito',      'MENU',     NULL, (SELECT ID_MENU FROM MENU WHERE CODIGO = 'MEN-001'),        50);

DECLARE
    PROCEDURE ABASTECER(COD VARCHAR2, CANT NUMBER, REF VARCHAR2) IS
        V_ID NUMBER;
    BEGIN
        SELECT ID_PRODUCTO INTO V_ID FROM PRODUCTO WHERE CODIGO = COD;
        PK_INVENTARIO.ABASTECER(V_ID, CANT, REF);
    END;
BEGIN
    ABASTECER('SAND-001', 10, 'CARGA-INICIAL');
    ABASTECER('BEB-001',  20, 'CARGA-INICIAL');
    ABASTECER('ACO-001',  15, 'CARGA-INICIAL');
    ABASTECER('SAND-002',  8, 'CARGA-INICIAL');
    ABASTECER('BEB-002',  10, 'CARGA-INICIAL');
    ABASTECER('ACO-002',  10, 'CARGA-INICIAL');
    ABASTECER('SAND-003',  6, 'CARGA-INICIAL');

    ABASTECER('SAND-001', 15, 'ABAST-2026-01');
    ABASTECER('BEB-001',  30, 'ABAST-2026-01');
    ABASTECER('ACO-001',  20, 'ABAST-2026-01');
END;
/
DECLARE
    V_JUAN   NUMBER;
    V_MARIA  NUMBER;
    V_CARLOS NUMBER;
    V_PED    NUMBER;
    V_BEB    NUMBER;

    PROCEDURE CREAR_PEDIDO(P_CLIENTE NUMBER, P_DET VARCHAR2, P_PAGO VARCHAR2, P_REFER VARCHAR2) IS
        V_SUBTOTAL NUMBER := 0;
        V_PUNTOS   NUMBER := 0;
    BEGIN
        INSERT INTO PEDIDO (ID_PEDIDO, ID_CLIENTE, SUBTOTAL, TOTAL, PUNTOS_GENERADOS, ESTADO)
        VALUES (SEQ_PEDIDO.NEXTVAL, P_CLIENTE, 0, 0, 0, 'PENDIENTE')
        RETURNING ID_PEDIDO INTO V_PED;

        IF INSTR(P_DET, 'MEN-001:2') > 0 THEN
            INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, V_PED, 'MENU', NULL,
                (SELECT ID_MENU FROM MENU WHERE CODIGO = 'MEN-001'), 2, 37.00, 74.00, 16);
            V_SUBTOTAL := V_SUBTOTAL + 74; V_PUNTOS := V_PUNTOS + 16;
        END IF;

        IF INSTR(P_DET, 'SAND-002:1') > 0 THEN
            INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, V_PED, 'PRODUCTO',
                (SELECT ID_PRODUCTO FROM PRODUCTO WHERE CODIGO = 'SAND-002'), NULL, 1, 22.00, 22.00, 2);
            V_SUBTOTAL := V_SUBTOTAL + 22; V_PUNTOS := V_PUNTOS + 2;
        END IF;

        IF INSTR(P_DET, 'BEB-001:1') > 0 THEN
            INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, V_PED, 'PRODUCTO',
                (SELECT ID_PRODUCTO FROM PRODUCTO WHERE CODIGO = 'BEB-001'), NULL, 1, 8.00, 8.00, 0);
            V_SUBTOTAL := V_SUBTOTAL + 8;
        END IF;

        IF INSTR(P_DET, 'MEN-002:1') > 0 THEN
            INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, V_PED, 'MENU', NULL,
                (SELECT ID_MENU FROM MENU WHERE CODIGO = 'MEN-002'), 1, 34.00, 34.00, 8);
            V_SUBTOTAL := V_SUBTOTAL + 34; V_PUNTOS := V_PUNTOS + 8;
        END IF;

        IF INSTR(P_DET, 'MEN-003:1') > 0 THEN
            INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, V_PED, 'MENU', NULL,
                (SELECT ID_MENU FROM MENU WHERE CODIGO = 'MEN-003'), 1, 39.00, 39.00, 8);
            V_SUBTOTAL := V_SUBTOTAL + 39; V_PUNTOS := V_PUNTOS + 8;
        END IF;

        UPDATE PEDIDO SET SUBTOTAL = V_SUBTOTAL, TOTAL = V_SUBTOTAL, PUNTOS_GENERADOS = V_PUNTOS
         WHERE ID_PEDIDO = V_PED;

        IF P_PAGO = 'EFECTIVO' THEN
            INSERT INTO PAGO (ID_PAGO, ID_PEDIDO, TIPO_PAGO, MONTO, EFECTIVO_RECIBIDO, CAMBIO, ESTADO)
            VALUES (SEQ_PAGO.NEXTVAL, V_PED, 'EFECTIVO', V_SUBTOTAL, CEIL(V_SUBTOTAL / 10) * 10,
                    CEIL(V_SUBTOTAL / 10) * 10 - V_SUBTOTAL, 'APROBADO');
        ELSE
            INSERT INTO PAGO (ID_PAGO, ID_PEDIDO, TIPO_PAGO, MONTO, REFERENCIA, ESTADO)
            VALUES (SEQ_PAGO.NEXTVAL, V_PED, 'TARJETA', V_SUBTOTAL, P_REFER, 'APROBADO');
        END IF;

        UPDATE PEDIDO SET ESTADO = 'PAGADO' WHERE ID_PEDIDO = V_PED;
    END;
BEGIN
    SELECT ID_CLIENTE INTO V_JUAN   FROM CLIENTE WHERE DPI = '12345678-1';
    SELECT ID_CLIENTE INTO V_MARIA  FROM CLIENTE WHERE DPI = '12345678-2';
    SELECT ID_CLIENTE INTO V_CARLOS FROM CLIENTE WHERE DPI = '12345678-3';

    PK_PUNTOS.ACREDITAR(V_JUAN, 20, 'AJUSTE-INICIAL');

    CREAR_PEDIDO(V_JUAN,   'MEN-001:2|SAND-002:1|BEB-001:1', 'EFECTIVO', NULL);
    CREAR_PEDIDO(V_MARIA,  'MEN-001:1|MEN-003:1',            'TARJETA',  'TX-99001');
    CREAR_PEDIDO(V_CARLOS, 'SAND-002:1|BEB-001:1',           'EFECTIVO', NULL);
    CREAR_PEDIDO(V_JUAN,   'MEN-002:1',                      'TARJETA',  'TX-99002');

    PK_PUNTOS.DESCONTAR(V_JUAN, 10, 'CANJE-REC-001');
    SELECT ID_PRODUCTO INTO V_BEB FROM PRODUCTO WHERE CODIGO = 'BEB-001';
    PK_INVENTARIO.DESCONTAR(V_BEB, 1, 'CANJE', 'CANJE-1');
    INSERT INTO CANJE (ID_CANJE, ID_CLIENTE, ID_RECOMPENSA, PUNTOS_USADOS)
    VALUES (SEQ_CANJE.NEXTVAL, V_JUAN, (SELECT ID_RECOMPENSA FROM RECOMPENSA WHERE CODIGO = 'REC-001'), 10);
END;
/
COMMIT;
