CREATE OR REPLACE VIEW VW_PUNTOS_CLIENTE AS
SELECT C.ID_CLIENTE,
       C.DPI,
       C.NOMBRE,
       C.ESTADO,
       C.SALDO_PUNTOS,
       NVL(SUM(CASE WHEN MP.TIPO_MOVIMIENTO = 'ACUMULACION' THEN MP.PUNTOS END), 0) AS TOTAL_ACUMULADO,
       NVL(SUM(CASE WHEN MP.TIPO_MOVIMIENTO = 'CANJE' THEN -MP.PUNTOS END), 0) AS TOTAL_CANJEADO,
       COUNT(MP.ID_MOVIMIENTO) AS TOTAL_MOVIMIENTOS
  FROM CLIENTE C
  LEFT JOIN MOVIMIENTO_PUNTOS MP ON MP.ID_CLIENTE = C.ID_CLIENTE
 GROUP BY C.ID_CLIENTE, C.DPI, C.NOMBRE, C.ESTADO, C.SALDO_PUNTOS;

CREATE OR REPLACE VIEW VW_INVENTARIO_CRITICO AS
SELECT P.ID_PRODUCTO,
       P.CODIGO,
       P.NOMBRE,
       P.CATEGORIA,
       P.EXISTENCIA
  FROM PRODUCTO P
 WHERE P.EXISTENCIA <= 5
   AND P.ESTADO = 'ACTIVO'
 ORDER BY P.EXISTENCIA, P.NOMBRE;

CREATE OR REPLACE VIEW VW_VENTAS_POR_PEDIDO AS
SELECT PE.ID_PEDIDO,
       PE.FECHA_PEDIDO,
       C.DPI,
       C.NOMBRE,
       PE.SUBTOTAL,
       PE.TOTAL,
       PE.PUNTOS_GENERADOS,
       PE.ESTADO,
       PA.TIPO_PAGO,
       PA.MONTO,
       PA.CAMBIO,
       PA.REFERENCIA,
       PA.ESTADO AS ESTADO_PAGO,
       PA.FECHA_PAGO
  FROM PEDIDO PE
  JOIN CLIENTE C  ON C.ID_CLIENTE = PE.ID_CLIENTE
  LEFT JOIN PAGO PA ON PA.ID_PEDIDO = PE.ID_PEDIDO;

CREATE OR REPLACE VIEW VW_VENTAS_UNIDADES AS
SELECT P.ID_PRODUCTO,
       P.CODIGO,
       P.NOMBRE,
       P.CATEGORIA,
       'VENTA DIRECTA' AS ORIGEN,
       SUM(DP.CANTIDAD) AS UNIDADES,
       SUM(DP.SUBTOTAL) AS IMPORTE
  FROM DETALLE_PEDIDO DP
  JOIN PEDIDO PE ON PE.ID_PEDIDO = DP.ID_PEDIDO
  JOIN PRODUCTO P ON P.ID_PRODUCTO = DP.ID_PRODUCTO
 WHERE DP.TIPO_ITEM = 'PRODUCTO'
   AND PE.ESTADO IN ('PAGADO', 'ENTREGADO')
 GROUP BY P.ID_PRODUCTO, P.CODIGO, P.NOMBRE, P.CATEGORIA
UNION ALL
SELECT P.ID_PRODUCTO,
       P.CODIGO,
       P.NOMBRE,
       P.CATEGORIA,
       'COMPONENTE DE MENU',
       SUM(DP.CANTIDAD * DM.CANTIDAD) AS UNIDADES,
       SUM(DP.SUBTOTAL) AS IMPORTE
  FROM DETALLE_PEDIDO DP
  JOIN PEDIDO PE       ON PE.ID_PEDIDO = DP.ID_PEDIDO
  JOIN DETALLE_MENU DM ON DM.ID_MENU = DP.ID_MENU
  JOIN PRODUCTO P      ON P.ID_PRODUCTO = DM.ID_PRODUCTO
 WHERE DP.TIPO_ITEM = 'MENU'
   AND PE.ESTADO IN ('PAGADO', 'ENTREGADO')
 GROUP BY P.ID_PRODUCTO, P.CODIGO, P.NOMBRE, P.CATEGORIA;
