PROMPT ===== 01. VENTAS POR PERIODO =====
SELECT V.TIPO_PAGO,
       COUNT(*)              AS CANTIDAD_PEDIDOS,
       SUM(V.TOTAL)          AS TOTAL_VENDIDO,
       SUM(V.CAMBIO)         AS TOTAL_CAMBIO
  FROM VW_VENTAS_POR_PEDIDO V
 WHERE V.ESTADO IN ('PAGADO', 'ENTREGADO')
   AND V.ESTADO_PAGO = 'APROBADO'
   AND V.FECHA_PEDIDO BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
 GROUP BY V.TIPO_PAGO
 ORDER BY V.TIPO_PAGO;

PROMPT ===== 01b. VENTAS POR PERIODO (TOTAL GENERAL) =====
SELECT COUNT(*)     AS CANTIDAD_PEDIDOS,
       NVL(SUM(V.TOTAL), 0) AS TOTAL_VENDIDO,
       NVL(SUM(CASE WHEN V.TIPO_PAGO = 'EFECTIVO' THEN V.TOTAL END), 0) AS TOTAL_EFECTIVO,
       NVL(SUM(CASE WHEN V.TIPO_PAGO = 'TARJETA'  THEN V.TOTAL END), 0) AS TOTAL_TARJETA
  FROM VW_VENTAS_POR_PEDIDO V
 WHERE V.ESTADO IN ('PAGADO', 'ENTREGADO')
   AND V.ESTADO_PAGO = 'APROBADO'
   AND V.FECHA_PEDIDO BETWEEN DATE '2026-01-01' AND DATE '2026-12-31';

PROMPT ===== 02. PRODUCTOS MAS VENDIDOS =====
SELECT VU.CODIGO,
       VU.NOMBRE,
       VU.CATEGORIA,
       VU.ORIGEN,
       VU.UNIDADES,
       VU.IMPORTE
  FROM VW_VENTAS_UNIDADES VU
 ORDER BY VU.UNIDADES DESC, VU.NOMBRE;

PROMPT ===== 02b. PRODUCTOS MAS VENDIDOS (CONSOLIDADO) =====
SELECT VU.CODIGO,
       VU.NOMBRE,
       VU.CATEGORIA,
       SUM(VU.UNIDADES) AS UNIDADES,
       SUM(VU.IMPORTE)  AS IMPORTE
  FROM VW_VENTAS_UNIDADES VU
 GROUP BY VU.CODIGO, VU.NOMBRE, VU.CATEGORIA
 ORDER BY UNIDADES DESC;

PROMPT ===== 03. PRODUCTOS AGOTADOS O CON BAJO INVENTARIO =====
SELECT V.CODIGO,
       V.NOMBRE,
       V.CATEGORIA,
       V.EXISTENCIA
  FROM VW_INVENTARIO_CRITICO V;

PROMPT ===== 04. PUNTOS ACUMULADOS POR CLIENTE =====
SELECT V.DPI,
       V.NOMBRE,
       V.ESTADO,
       V.TOTAL_ACUMULADO,
       V.TOTAL_CANJEADO,
       V.SALDO_PUNTOS
  FROM VW_PUNTOS_CLIENTE V
 ORDER BY V.SALDO_PUNTOS DESC, V.NOMBRE;

PROMPT ===== 05. HISTORIAL DE CANJES =====
SELECT CA.ID_CANJE,
       CA.FECHA_CANJE,
       C.DPI,
       C.NOMBRE,
       R.CODIGO AS RECOMPENSA,
       R.NOMBRE AS NOMBRE_RECOMPENSA,
       CA.PUNTOS_USADOS
  FROM CANJE CA
  JOIN CLIENTE C    ON C.ID_CLIENTE = CA.ID_CLIENTE
  JOIN RECOMPENSA R ON R.ID_RECOMPENSA = CA.ID_RECOMPENSA
 ORDER BY CA.FECHA_CANJE DESC, CA.ID_CANJE DESC;

PROMPT ===== 06. VENTAS DE MENUS COMPLETOS =====
SELECT M.CODIGO,
       M.NOMBRE,
       SUM(DP.CANTIDAD)  AS CANTIDAD,
       SUM(DP.SUBTOTAL) AS IMPORTE,
       SUM(DP.PUNTOS)   AS PUNTOS
  FROM DETALLE_PEDIDO DP
  JOIN PEDIDO PE ON PE.ID_PEDIDO = DP.ID_PEDIDO
  JOIN MENU M    ON M.ID_MENU = DP.ID_MENU
 WHERE DP.TIPO_ITEM = 'MENU'
   AND PE.ESTADO IN ('PAGADO', 'ENTREGADO')
   AND PE.FECHA_PEDIDO BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
 GROUP BY M.CODIGO, M.NOMBRE
 ORDER BY CANTIDAD DESC;

PROMPT ===== 07. HISTORIAL DE MOVIMIENTOS DE PUNTOS =====
SELECT MP.FECHA_MOVIMIENTO,
       C.DPI,
       C.NOMBRE,
       MP.TIPO_MOVIMIENTO,
       MP.PUNTOS,
       MP.SALDO_RESULTANTE,
       MP.REFERENCIA
  FROM MOVIMIENTO_PUNTOS MP
  JOIN CLIENTE C ON C.ID_CLIENTE = MP.ID_CLIENTE
 WHERE C.DPI = '12345678-1'
 ORDER BY MP.FECHA_MOVIMIENTO, MP.ID_MOVIMIENTO;

PROMPT ===== 08. HISTORIAL DE MOVIMIENTOS DE INVENTARIO =====
SELECT MI.FECHA_MOVIMIENTO,
       P.CODIGO,
       P.NOMBRE,
       MI.TIPO_MOVIMIENTO,
       MI.CANTIDAD,
       MI.EXISTENCIA_ANTERIOR,
       MI.EXISTENCIA_NUEVA,
       MI.REFERENCIA
  FROM MOVIMIENTO_INVENTARIO MI
  JOIN PRODUCTO P ON P.ID_PRODUCTO = MI.ID_PRODUCTO
 ORDER BY MI.FECHA_MOVIMIENTO DESC, MI.ID_MOVIMIENTO DESC;
